name: CI/CD pipeline
on:
  push:
    branches: ["main", "fix/env-vars-backend"]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ATLAS_URI: "${{ secrets.ATLAS_URI }}"
          PROD_DB: "${{ secrets.PROD_DB }}"
          DEV_DB: "${{ secrets.DEV_DB }}"
          UNLABELED_RESUME_COLLECTION: "${{ secrets.UNLABELED_RESUME_COLLECTION }}"
          LABELED_RESUME_COLLECTION: "${{ secrets.LABELED_RESUME_COLLECTION }}"
      - run: "make create-env"
      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - id: "deploy"
        uses: "google-github-actions/deploy-appengine@v0"
        with:
          working_directory: ./root/backend
          deliverables: app.yaml
