name: CI/CD dev-pipeline
on:
  push:
    branches: ["dev"]

jobs:
  backend:
    runs-on: ubuntu-latest
    env:
      ATLAS_URI: "${{ secrets.ATLAS_URI }}"
      DB: "${{ secrets.DEV_DB }}"
      UNLABELED_RESUME_COLLECTION: "${{ secrets.UNLABELED_RESUME_COLLECTION }}"
      LABELED_RESUME_COLLECTION: "${{ secrets.LABELED_RESUME_COLLECTION }}"
      STORAGE_BUCKET: "dev-p4ds-job-title-kw"
    steps:
      - uses: actions/checkout@v3

      - run: "make create-env"

      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - run: gcloud auth configure-docker

      - id: "docker_build"
        run: make build-and-deploy-dev-image

      - id: "deploy"
        uses: "google-github-actions/deploy-appengine@v0"
        with:
          working_directory: ./root/backend/deployment/dev
          deliverables: app.yaml
