# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI/CD pipeline

on:
  push:
    branches: ["main", "feat/backend-deploy"]
  pull_request:
    branches: ["main"]

jobs:
  deploybackend:
    defaults:
      run:
        working-directory: ./root/backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - id: 'deploy'
      uses: 'google-github-actions/deploy-appengine@v0'
      deliverables: ./root/backend/app.yaml

  build:
    defaults:
      run:
        working-directory: ./root/frontend/

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "./root/frontend/package-lock.json"

      # Run a clean install of dependencies
      - run: npm ci
      # Build project
      - run: npm run build --if-present
      # Run all tests
      - run: npm test a
