FROM python:3.9-slim

WORKDIR /app
COPY requirements.txt ./

RUN apt-get update

RUN pip install -U pip
RUN pip install -r requirements.txt
# RUN pip install https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.1/en_core_sci_sm-0.5.1.tar.gz
# RUN python -m spacy link https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.1/en_core_sci_sm-0.5.1.tar.gz en_core_sci_sm 

RUN python3 -m spacy download en_core_web_sm 

COPY . /app


EXPOSE 8080
CMD ["python3", "main.py"]
