FROM python:3.9-slim

WORKDIR /app
COPY requirements.txt ./

RUN apt-get update

RUN apt-get update && \
        apt-get install -y \
            wget \
            xzdec \
            cm-super \
            texlive \
            texlive-xetex \
            texlive-fonts-extra \
            texinfo \
            && \
        apt-get clean && \
        rm -rf /var/lib/apt/*

RUN mkdir /root/tetxf
RUN tlmgr init-usertree
RUN tlmgr install ucharcat


RUN pip install -U pip
RUN pip install -r requirements.txt

RUN python3 -m spacy download en_core_web_sm 

COPY . /app


EXPOSE 8080
CMD ["python3", "main.py"]
